name: Smallsemi
version: 0.6.11
date: 2017-04-26
description: |
    A library of small semigroups

authors:
    - name: Andreas Distler
      url: mailto:a.distler@tu-bs.de
    - name: James Mitchell
      url: http://tinyurl.com/jdmitchell

maintainers:
    - name: Andreas Distler
      url: mailto:a.distler@tu-bs.de
    - name: James Mitchell
      url: http://tinyurl.com/jdmitchell

GAP: ">=4.8"

www: https://gap-packages.github.io/smallsemi/
readme: README
packageinfo: https://gap-packages.github.io/smallsemi/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/smallsemi/releases/download/v0.6.11/smallsemi-0.6.11.tar.gz

abstract: |
    The <Package>Smallsemi</Package> package is a data library of semigroups    of small size. It provides all semigroups with at most 8 elements as well    as various information about these objects.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    small semigroups, data library, multiplication tables.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>DM17</span>]   <b class='BibAuthor'>Distler, A. and Mitchell, J.</b>,
     <i class='BibTitle'>Smallsemi, A library of small semigroups,
             Version 0.6.11</i>
     (<span class='BibYear'>2017</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/smallsemi/">https://gap-packages.github.io/smallsemi/</a></span>.
    </p>
    

bibtex: |
    @misc{ Smallsemi0.6.11,
      author =           {Distler, A. and Mitchell, J.},
      title =            {{Smallsemi}, A library of small semigroups, {V}ersion 0.6.11},
      month =            {Apr},
      year =             {2017},
      note =             {GAP package},
      howpublished =     {\href {https://gap-packages.github.io/smallsemi/} {\texttt{https://gap-packages.github.io/}\discretionary {}{}{}\texttt{smallsemi/}}},
      keywords =         {small semigroups; data library; multiplication tables},
      printedkey =       {DM17}
    }

